inputs:
    files: [../data_shared/effmaps/AnalysisResults_LHC24k3_trackTuner_ptSmearing1p5_phiDep.root]
    weights: [1.] #0.107, 0.747] # weights to be assigned in case of different sampling used in different MC productions (values obtained from integrated luminosity)

pt_mins: [0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16.]
pt_maxs: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16., 50.]
bdtbkg_cuts: [0.05, 0.05, 0.05, 0.1, 0.2, 0.2, 0.3, 0.35, 0.4, 0.5, 0.5, 0.5, 0.5]

outputs:
    efficiencies: ../data_shared/axeD0.root
    reflections: ../data_shared/reflections_d0.root
