---
inputs:
  #data: ../data_shared/2022_pass7_skimmed/fDiMuon/tree_jpsi_d0_reduced_data_merged_std_assoc_LHC22Pass7_BDT_modular_cut_weighted.root
  #tree: "DF_2249150152204455/O2rtdilptdmesall"
  #inputLabel: "LHC22Pass7"
  #data: ../data_shared/2023_pass4_skimmed/fDiMuon/tree_jpsi_d0_reduced_data_merged_std_assoc_LHC23Pass4_BDT_modular_cut_weighted.root
  #tree: "DF_2298103923608640/O2rtdilptdmesall"
  #inputLabel: "LHC23Pass4"
  data: ../data_shared/2024_pass1_skimmed/fDiMuon/tree_jpsi_d0_reduced_data_merged_std_assoc_LHC24Pass1_BDT_modular_cut_weighted.root
  #tree: "DF_2365874330435264/O2rtdilptdmesall"
  inputLabel: "LHC24Pass1"

  tree: "O2rtdilptdmesall"
  hist: hSparseJPsiDmeson_proj_3_2
  axeJpsi: ../data_shared/axeJpsiToMuMu.root
  axeD0: ../data_shared/axeD0.root
  
reflections:
  data: /Users/bat/alice/jpsiHF/reflections_D0_cuts.root
  refl: hist_refl_smooth
  signal: hist_signal

prefilter:  
  data: ../data_shared/2022_pass7_skimmed/fDiMuon/tree_jpsi_d0_reduced_data_merged_std_assoc_LHC22Pass7.root
  tree: "DF_2249150152204455/O2rtdilptdmesall"
  #data: ../data_shared/2023_pass4_skimmed/fDiMuon/tree_jpsi_d0_reduced_data_merged_std_assoc_LHC23Pass4.root
  #tree: "DF_2298103923608640/O2rtdilptdmesall"
  #data: ../data_shared/2024_pass1_skimmed/fDiMuon/tree_jpsi_d0_reduced_data_merged_std_assoc_LHC24Pass1.root
  #tree: "DF_2365874330435264/O2rtdilptdmesall"
  cuts: "(fPtDmes >= 0.  && fPtDmes < 1.  && fBdtBkg < 0.050) ||
         (fPtDmes >= 1.  && fPtDmes < 2.  && fBdtBkg < 0.050) ||
         (fPtDmes >= 2.  && fPtDmes < 3.  && fBdtBkg < 0.100) ||
         (fPtDmes >= 3.  && fPtDmes < 4.  && fBdtBkg < 0.100) ||
         (fPtDmes >= 4.  && fPtDmes < 6.  && fBdtBkg < 0.200) ||
         (fPtDmes >= 6.  && fPtDmes < 8.  && fBdtBkg < 0.300) ||
         (fPtDmes >= 8.  && fPtDmes < 10. && fBdtBkg < 0.300) ||
         (fPtDmes >= 10. && fPtDmes < 20. && fBdtBkg < 0.500) ||
         (fPtDmes >= 20. && fPtDmes < 50. && fBdtBkg < 0.500)"
  suffix: _BDT_modular_cut


fit:
  toy_mc: False
  unbinned: True
  weighted: True
  min_fit_range_d0: 1.70
  max_fit_range_d0: 2.05
  min_fit_range_jpsi: 2.5
  max_fit_range_jpsi: 4.00
  JpsiChannel: "Jpsi2mumu"
  add_psi2s: True ## if true, the psi2s is added to the fit

  min_jpsi_rap : -4
  max_jpsi_rap : -2.6

  min_jpsi_pt : 0
  max_jpsi_pt : 100

  min_d0_rap : -0.6
  max_d0_rap : 0.6

  min_d0_pt : 0.5
  max_d0_pt : 100

  min_dRap : 0
  max_dRap : 100
  
  
  norm_par_sig_name: [nJPsiD0, nBkgJPsi, nBkgD0, nBkgBkg, rPsi2sJPsi]
  norm_par_sig_val: [50000, 10000, 2000, 10000, 0.023]
  norm_par_sig_lw_lim: [500, 100, 20, 100, 0.02]
  norm_par_sig_up_lim: [500000, 10000000, 20000000, 100000000, 0.03]
  norm_par_sig_is_const: [False, False, False, False, True]

  cb_par_jpsi_name: [meanJpsi, sigmaJpsi, alphaJpsi, nJpsi]
  cb_par_jpsi_val: [3.0813e+00, 7.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_jpsi_lw_lim: [2.9000e+00, 5.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_jpsi_up_lim: [3.2000e+00, 9.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_jpsi_is_const: [False, False, True, True]

  cb_par_psi2s_name: [meanPsi2s, sigmaPsi2s, alphaPsi2s, nPsi2s]
  cb_par_psi2s_val: [3.68609e+00, 8.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_psi2s_lw_lim: [3.6000e+00, 7.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_psi2s_up_lim: [3.8000e+00, 9.5466e-02, 1.0725e+00, 1.0000e+01]
  cb_par_psi2s_is_const: [False, False, True, True]

  cheby_par_jpsi_name: [cheb_coeff_jpsi_0, cheb_coeff_jpsi_1, cheb_coeff_jpsi_2]
  cheby_par_jpsi_val: [-8.8e-01, 3.0e-01, -8.3e-02]
  cheby_par_jpsi_lw_lim: [-1, -1, -1]
  cheby_par_jpsi_up_lim: [1, 1, 1]
  cheby_par_jpsi_is_const: [False, False, False]

  cb_par_d0_name: [meanD0, sigmaD0, alphaD0, nD0]
  cb_par_d0_val: [1.8592e+00, 1.5980e-02, 3.2386e+00, 2.3591e-09]
  cb_par_d0_lw_lim: [1.7592e+00, 1.0e-02, 3.2386e+00, 2.3591e-09]
  cb_par_d0_up_lim: [1.9592e+00, 3.0e-02, 3.2386e+00, 2.3591e-09]
  cb_par_d0_is_const: [False, False, True, True]

  cheby_par_d0_name: [cheb_coeff_d0_0, cheb_coeff_d0_1, cheb_coeff_d0_2]
  cheby_par_d0_val: [-5.e-01, 8.1e-02, 1.230e-08]
  cheby_par_d0_lw_lim: [-1, -1, -1]
  cheby_par_d0_up_lim: [1, 1, 1]
  cheby_par_d0_is_const: [False, False, False]

plot_results:
  dataBins: 50
  jpsiFrame:
    x_title: "#it{m}_{#mu#mu} (GeV/#it{c}^{2})"
    y_title: ## if you want to use the default title, just leave it empty
    x_title_offset: 1.1
    y_title_offset: 2.1
    x_range: [2.51, 4.0]
    y_range: [0.1, 300000]
    y_range_log: [1.1, 1.e+9]
    y_title_offset_log: 1.5
  d0Frame:
    x_title: "#it{m}_{#piK} (GeV/#it{c}^{2})"
    y_title: ## if you want to use the default title, just leave it empty
    x_title_offset: 1.1
    y_title_offset: 2.1
    x_range: [1.7, 2.05]
    y_range: [0.1, 200000]
    y_range_log: [1.1, 1.e+9]

output:
  directory: outputs_skimming
  figures: figures_skimming
