hadron: dzero

input:
  data: ../../data_shared/2024_pass1_minbias/AnalysisResults_LHC24_minBias_sampled_D0.root
  mc: [../../data_shared/effmaps/AnalysisResults_LHC24k3_trackTuner_ptSmearing1p5_phiDep.root]
  corrbkg: [../../data_shared/effmaps/AnalysisResults_LHC24k3_trackTuner_ptSmearing1p5_phiDep.root]
  mc_weights: [1.] # if only one file ignored

pt_mins: [0.5, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16.]
pt_maxs: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10., 12., 16., 24.]
bdt_cuts:
  bkg: [0.05, 0.05, 0.05, 0.1, 0.2, 0.2, 0.3, 0.35, 0.4, 0.5, 0.5, 0.5, 0.5]
  nonprompt: [0.10, 0.12, 0.14, 0.16, 0.18,
              0.20, 0.22, 0.24, 0.26, 0.28,
              0.30, 0.32, 0.34, 0.36, 0.38,
              0.40, 0.42, 0.44, 0.46, 0.48,
              0.50, 0.52, 0.54, 0.56, 0.58,
              0.60, 0.62, 0.64, 0.66, 0.68,
              0.70, 0.72, 0.74, 0.76, 0.78,
              0.80, 0.82, 0.84, 0.86, 0.88,
              0.90, 0.92, 0.94, 0.96, 0.98] # values for cut-variation method (pT differential?)

fit:
  mass_mins: [1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72, 1.72] 
  mass_maxs: [2.05, 2.05, 2.05, 2.05, 2.05, 2.05, 2.05, 2.05, 2.05, 2.05, 2.05, 2.10, 2.10] 
  sgn_funcs: ["gaussian", "gaussian", "gaussian", "gaussian", "gaussian", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb", "doublecb"]
  bkg_funcs: ["chebpol3", "chebpol3", "chebpol3", "chebpol2", "chebpol2", "chebpol2", "chebpol2", "chebpol2", "chebpol2", "chebpol2", "chebpol2", "chebpol2", "chebpol2"]
  fix_frac_bkgcorr: [True, True, True, True, True, True, True, True, True, True, True, True, True]
  fix_tailpars_from_mc: [False, False, False, False, False, True, True, True, True, True, True, True, True]

efficiency:
  include_pitomu: True
  y_gen: 0.5

output:
  rawyields:
    directory: rawyields
    suffix: _dzero_LHC24_JPsiD
  efficiencies:
    directory: efficiencies
    suffix: _dzero_LHC24k3_trackTuner_ptSmearing1p5_JPsiD
